import ExactAttention.OpenPath

/-!
# The derivative field of an execution (`thm:history`)

This file formalizes `sec:history` and the counting step in the proof of `thm:attention`.

**Traces.** An execution on an open path is abstracted as a `History.Trace F K W ι`. Here `K` is
a field (the fraction field of analytic functions on the open execution set in the paper, see
`AnalyticFunctionField`), `F` is a base field mapped into `K` (the rational functions `ℝ(x)`),
`W` names the words of both memories (fast registers and slow addresses), and `ι` indexes the
input coordinates (`Fin p` in the paper). The trace records:

* `row t w : ι → K`, the first derivative row of word `w` after `t` epochs. Every word has a
  row, and initially all row entries lie in `F` (inputs, constants and unwritten words have
  derivative entries `0` or `1`).
* `e` epochs, where epoch `t < e` has `xfer t ≤ M` transfers, and exactly `M` unless it is the
  last one (`eq:epochs`).
* For epoch `t`, incoming words `inc t : Fin (a t) → W` with `a t ≤ 2 M`, whose current rows form
  the `a t × p` matrix DC_t, outgoing words `out t : Fin (b t) → W` with `b t ≤ 2 M` (stores and
  final cache), and a local Jacobian `Λ t`, a `b t × a t` matrix over `K`. After the epoch, each
  word either keeps its row or is an outgoing word `out t i` whose new row is row `i` of the
  product `Λ t` DC_t (`eq:chain`). When a word is written several times in one epoch, its last
  version is the one that survives.

The facts that the outgoing values of an epoch are an analytic function `Φ_t` of the incoming
ones (`lem:boundary`) and that `DB_t = Λ_t DC_t` with `Λ_t = DΦ_t ∘ C_t` (`eq:chain`) belong to
the analytic layer; the trace hypotheses encode them. For straight-line expressions we prove both
here: `boundary_factorization` gives the local analytic map at a realised boundary point, and
`epoch_chain_rule` gives the matrix chain rule `DB = Λ DC` (built on `chain_rule_jacobian`).

**Results.** `History.Trace.row_mem_history` is the induction behind `eq:history`: after `t`
epochs every row entry of every word lies in `H_t = F(entries of Λ_0, …, Λ_{t-1})`.
`history_bound` is `thm:history`: the transcendence degree over `F` of the field generated by the
output derivative rows is at most `∑ a_t b_t ≤ 4 M² e`, and `I ≥ τ/(4M) - M`. `epochs_le` is
`eq:epochs`. `attention_bound_of_trace` is the deduction of `eq:main-lower` in the proof of
`thm:attention`, from `n(n-1)` algebraically independent output derivatives and `nd` output
stores.
-/

namespace ExactAttention

open Cardinal

namespace History

section General

variable {F K : Type*} [Field F] [Field K] [Algebra F K]

/-- Adjoining a set raises the transcendence degree by at most its cardinality. -/
theorem trdeg_adjoin_le (S : Set K) :
    Algebra.trdeg F (IntermediateField.adjoin F S) ≤ #S := by
  set A := IntermediateField.adjoin F S
  set s : Set A := A.val ⁻¹' S with hs
  have : Algebra.IsAlgebraic (Algebra.adjoin F s) A := by
    refine ⟨fun a => ?_⟩
    obtain ⟨r, hr, t, ht, hrt⟩ := IntermediateField.mem_adjoin_iff_div.mp a.2
    have hmap : (Algebra.adjoin F s).map A.val = Algebra.adjoin F S := by
      rw [AlgHom.map_adjoin, hs, Set.image_preimage_eq_of_subset]
      intro x hx
      exact ⟨⟨x, IntermediateField.subset_adjoin F S hx⟩, rfl⟩
    rw [← hmap] at hr ht
    obtain ⟨r', hr', rfl⟩ := Subalgebra.mem_map.mp hr
    obtain ⟨t', ht', rfl⟩ := Subalgebra.mem_map.mp ht
    by_cases ht0 : t' = 0
    · have : a = 0 := by
        ext
        simp [hrt, ht0]
      rw [this]
      exact isAlgebraic_zero
    · refine IsAlgebraic.of_smul (y := (⟨t', ht'⟩ : Algebra.adjoin F s))
        (mem_nonZeroDivisors_of_ne_zero fun h => ht0 (congrArg Subtype.val h)) ?_
      have ht0' : (A.val t' : K) ≠ 0 := by
        simpa using ht0
      have : (⟨t', ht'⟩ : Algebra.adjoin F s) • a =
          algebraMap (Algebra.adjoin F s) A ⟨r', hr'⟩ := by
        apply Subtype.ext
        simp only [Subalgebra.smul_def, smul_eq_mul, IntermediateField.coe_mul,
          Subalgebra.algebraMap_eq, Algebra.algebraMap_self]
        change (A.val t') * (A.val a) = A.val r'
        rw [show A.val a = (a : K) from rfl, hrt]
        field_simp
      rw [this]
      exact isAlgebraic_algebraMap _
  calc Algebra.trdeg F A ≤ #s := Algebra.IsAlgebraic.trdeg_le_cardinalMk F s
    _ ≤ #S := Cardinal.mk_preimage_of_injective _ _ A.val.injective

end General

/-- An execution traced through first derivatives, epoch by epoch. See the file header. -/
structure Trace (F K W ι : Type*) [Field F] [Field K] [Algebra F K] where
  /-- The number of fast words. -/
  M : ℕ
  /-- The number of epochs. -/
  e : ℕ
  /-- The number of transfers in each epoch. -/
  xfer : ℕ → ℕ
  /-- The number of incoming values of each epoch. -/
  a : ℕ → ℕ
  /-- The number of outgoing values of each epoch. -/
  b : ℕ → ℕ
  /-- The words whose current versions are the incoming values of an epoch. -/
  inc : (t : ℕ) → Fin (a t) → W
  /-- The words written by the outgoing values of an epoch. -/
  out : (t : ℕ) → Fin (b t) → W
  /-- The local Jacobian of an epoch. -/
  Λ : (t : ℕ) → Matrix (Fin (b t)) (Fin (a t)) K
  /-- The first derivative row of each word after `t` epochs. -/
  row : ℕ → W → ι → K
  M_pos : 0 < M
  /-- Each epoch has at most `M` transfers. -/
  xfer_le : ∀ t < e, xfer t ≤ M
  /-- Every epoch except the last has exactly `M` transfers. -/
  xfer_eq : ∀ t, t + 1 < e → xfer t = M
  /-- At most `M` initial cache values and `M` loads enter an epoch. -/
  a_le : ∀ t < e, a t ≤ 2 * M
  /-- At most `M` stores and `M` final cache values leave an epoch. -/
  b_le : ∀ t < e, b t ≤ 2 * M
  /-- Initial derivative entries lie in the base field. -/
  row_zero : ∀ w j, row 0 w j ∈ Set.range (algebraMap F K)
  /-- `eq:chain`: a word changed by epoch `t` is an outgoing word whose row is the matching row of
  `Λ t` times the incoming rows; every other word keeps its row. -/
  step : ∀ t < e, ∀ w,
    (∃ i, out t i = w ∧ row (t + 1) w = (Λ t * Matrix.of fun k j => row t (inc t k) j) i) ∨
      row (t + 1) w = row t w

namespace Trace

variable {F K W ι : Type*} [Field F] [Field K] [Algebra F K] (T : Trace F K W ι)

/-- The total number of transfers. -/
def I : ℕ := ∑ t ∈ Finset.range T.e, T.xfer t

/-- The entries of the local Jacobians of the first `t` epochs. -/
def jacEntries (t : ℕ) : Set K :=
  Set.range fun x : (Σ s : Fin t, Fin (T.b s) × Fin (T.a s)) => T.Λ x.1 x.2.1 x.2.2

/-- The history field `H_t` of `eq:history`: `F` with all local Jacobian entries of the first `t`
epochs adjoined. -/
def history (t : ℕ) : IntermediateField F K := IntermediateField.adjoin F (T.jacEntries t)

/-- The field generated over `F` by the final derivative rows of the words in `O`. -/
def outputField (O : Set W) : IntermediateField F K :=
  IntermediateField.adjoin F {x | ∃ w ∈ O, ∃ j, T.row T.e w j = x}

theorem history_mono {t t' : ℕ} (h : t ≤ t') : T.history t ≤ T.history t' := by
  refine IntermediateField.adjoin.mono F _ _ ?_
  rintro _ ⟨⟨s, i, k⟩, rfl⟩
  exact ⟨⟨⟨s, by omega⟩, i, k⟩, rfl⟩

theorem entry_mem_history {s t : ℕ} (h : s < t) (i : Fin (T.b s)) (k : Fin (T.a s)) :
    T.Λ s i k ∈ T.history t :=
  IntermediateField.subset_adjoin F _ ⟨⟨⟨s, h⟩, i, k⟩, rfl⟩

/-- **The history induction** (`eq:history`, proof of `thm:history`). After `t` epochs, every
derivative entry of every word lies in `H_t`. -/
theorem row_mem_history : ∀ t ≤ T.e, ∀ w j, T.row t w j ∈ T.history t := by
  intro t
  induction t with
  | zero =>
    intro _ w j
    obtain ⟨c, hc⟩ := T.row_zero w j
    rw [← hc]
    exact IntermediateField.algebraMap_mem _ c
  | succ t ih =>
    intro ht w j
    have hmono := T.history_mono (Nat.le_succ t)
    rcases T.step t (by omega) w with ⟨i, -, hrow⟩ | hrow
    · rw [hrow, Matrix.mul_apply]
      refine IntermediateField.sum_mem _ fun k _ => IntermediateField.mul_mem _ ?_ ?_
      · exact T.entry_mem_history (Nat.lt_succ_self t) i k
      · exact hmono (ih (by omega) _ _)
    · rw [hrow]
      exact hmono (ih (by omega) w j)

theorem outputField_le_history (O : Set W) : T.outputField O ≤ T.history T.e := by
  rw [outputField, IntermediateField.adjoin_le_iff]
  rintro _ ⟨w, -, j, rfl⟩
  exact T.row_mem_history T.e le_rfl w j

/-- Adjoining the `a_s b_s` entries of each local Jacobian bounds the transcendence degree of the
history field. -/
theorem trdeg_history_le (t : ℕ) :
    Algebra.trdeg F (T.history t) ≤ ((∑ s ∈ Finset.range t, T.a s * T.b s : ℕ) : Cardinal) := by
  classical
  refine (trdeg_adjoin_le _).trans ?_
  rw [jacEntries, Cardinal.mk_fintype, Nat.cast_le]
  refine (Fintype.card_range_le _).trans_eq ?_
  rw [Fintype.card_sigma]
  simp only [Fintype.card_prod, Fintype.card_fin]
  rw [Fin.sum_univ_eq_sum_range (fun s => T.b s * T.a s) t]
  exact Finset.sum_congr rfl fun s _ => Nat.mul_comm _ _

/-- All epochs but the last carry `M` transfers. -/
theorem mul_e_le : T.M * T.e ≤ T.I + T.M := by
  rcases Nat.eq_zero_or_eq_succ_pred T.e with he | he
  · rw [he]
    omega
  · have hsum : ∑ t ∈ Finset.range (T.e - 1), T.M ≤ ∑ t ∈ Finset.range (T.e - 1), T.xfer t :=
      Finset.sum_le_sum fun t ht => (T.xfer_eq t (by simp at ht; omega)).ge
    have hI : ∑ t ∈ Finset.range (T.e - 1), T.xfer t ≤ T.I := by
      rw [I, he, Finset.sum_range_succ]
      simp
    simp only [Finset.sum_const, Finset.card_range, smul_eq_mul] at hsum
    rw [he, Nat.mul_succ]
    have := hsum.trans hI
    rw [show T.e - 1 = T.e.pred from rfl] at this
    nlinarith [this]

theorem sum_ab_le : ∑ t ∈ Finset.range T.e, T.a t * T.b t ≤ 4 * T.M ^ 2 * T.e := by
  calc ∑ t ∈ Finset.range T.e, T.a t * T.b t ≤ ∑ t ∈ Finset.range T.e, (2 * T.M) * (2 * T.M) :=
        Finset.sum_le_sum fun t ht => by
          have ht' := Finset.mem_range.mp ht
          exact Nat.mul_le_mul (T.a_le t ht') (T.b_le t ht')
    _ = 4 * T.M ^ 2 * T.e := by
        rw [Finset.sum_const, Finset.card_range, smul_eq_mul]
        ring

end Trace

end History

open History

variable {F K W ι : Type*} [Field F] [Field K] [Algebra F K]

/-- **Epoch count** (`eq:epochs`). An execution with `I` transfers, split into epochs of `M`
transfers except possibly the last, has at most `I/M + 1` epochs. -/
theorem epochs_le (T : Trace F K W ι) : (T.e : ℝ) ≤ T.I / T.M + 1 := by
  have hM : (0 : ℝ) < T.M := by exact_mod_cast T.M_pos
  have h : (T.M : ℝ) * T.e ≤ T.I + T.M := by exact_mod_cast T.mul_e_le
  rw [← sub_le_iff_le_add, le_div_iff₀ hM]
  nlinarith

/-- **I/O and the first-derivative field** (`thm:history`). For any set `O` of output words, let
`τ` be the transcendence degree over `F` of the field generated by their final derivative rows.
Then `τ` is finite, `τ ≤ trdeg_F H_e ≤ ∑ a_t b_t ≤ 4 M² e`, and `I ≥ τ/(4M) - M`
(`eq:history-bound`). -/
theorem history_bound (T : Trace F K W ι) (O : Set W) :
    ∃ τ : ℕ, Algebra.trdeg F (T.outputField O) = τ ∧
      (τ : Cardinal) ≤ Algebra.trdeg F (T.history T.e) ∧
      Algebra.trdeg F (T.history T.e) ≤ ((∑ t ∈ Finset.range T.e, T.a t * T.b t : ℕ) : Cardinal) ∧
      ∑ t ∈ Finset.range T.e, T.a t * T.b t ≤ 4 * T.M ^ 2 * T.e ∧
      (τ : ℝ) / (4 * T.M) - T.M ≤ T.I := by
  have h0 : Algebra.trdeg F (T.outputField O) ≤ Algebra.trdeg F (T.history T.e) :=
    trdeg_le_of_injective (IntermediateField.inclusion (T.outputField_le_history O))
      (IntermediateField.inclusion_injective _)
  have h1 := T.trdeg_history_le T.e
  have hfin : Algebra.trdeg F (T.outputField O) < Cardinal.aleph0 :=
    (h0.trans h1).trans_lt (Cardinal.natCast_lt_aleph0)
  set τ := (Algebra.trdeg F (T.outputField O)).toNat
  have hτeq : Algebra.trdeg F (T.outputField O) = τ := (Cardinal.cast_toNat_of_lt_aleph0 hfin).symm
  refine ⟨τ, hτeq, hτeq ▸ h0, h1, T.sum_ab_le, ?_⟩
  have hτ : τ ≤ 4 * T.M ^ 2 * T.e := by
    refine le_trans ?_ T.sum_ab_le
    have := h0.trans h1
    rw [hτeq] at this
    exact_mod_cast this
  have hM : (0 : ℝ) < T.M := by exact_mod_cast T.M_pos
  have hτ' : (τ : ℝ) ≤ 4 * T.M ^ 2 * T.e := by exact_mod_cast hτ
  have he : (T.M : ℝ) * T.e ≤ T.I + T.M := by exact_mod_cast T.mul_e_le
  rw [sub_le_iff_le_add, div_le_iff₀ (by positivity)]
  nlinarith

/-- **The counting step of `thm:attention`** (`eq:main-lower`). Suppose the output derivative
field contains a family of at least `n(n-1)` elements that are algebraically independent over
`F`, with `n ≥ 2` and `d ≥ 2`, and the execution makes at least `nd` transfers (the compulsory
output stores). Then `I ≥ (nd + n²/M)/32`. -/
theorem attention_bound_of_trace (T : Trace F K W ι) (O : Set W) {n d : ℕ} (hn : 2 ≤ n)
    (hd : 2 ≤ d) {κ : Type*} [Fintype κ] (hκ : n * (n - 1) ≤ Fintype.card κ) (r : κ → K)
    (hr : AlgebraicIndependent F r)
    (hrO : ∀ i, r i ∈ T.outputField O) (hI : n * d ≤ T.I) :
    ((n * d : ℝ) + (n : ℝ) ^ 2 / T.M) / 32 ≤ T.I := by
  have hr' : AlgebraicIndependent F (fun i => (⟨r i, hrO i⟩ : T.outputField O)) :=
    AlgebraicIndependent.of_comp (T.outputField O).val hr
  have hcard := hr'.lift_cardinalMk_le_trdeg
  obtain ⟨τ, hτeq, hτH, hH, hsum, -⟩ := history_bound T O
  rw [hτeq] at hcard
  simp only [Cardinal.mk_fintype, Cardinal.lift_natCast] at hcard
  have hle : n * (n - 1) ≤ ∑ t ∈ Finset.range T.e, T.a t * T.b t := by
    have h1 : Fintype.card κ ≤ τ := by exact_mod_cast hcard
    have h2 : τ ≤ ∑ t ∈ Finset.range T.e, T.a t * T.b t := by exact_mod_cast hτH.trans hH
    exact hκ.trans (h1.trans h2)
  have hτ : n * (n - 1) ≤ 4 * T.M ^ 2 * T.e := hle.trans hsum
  have hM : (0 : ℝ) < T.M := by exact_mod_cast T.M_pos
  have he : (T.M : ℝ) * T.e ≤ T.I + T.M := by exact_mod_cast T.mul_e_le
  have hτ' : (n : ℝ) * (n - 1) ≤ 4 * T.M ^ 2 * T.e := by
    have : ((n * (n - 1) : ℕ) : ℝ) ≤ 4 * T.M ^ 2 * T.e := by exact_mod_cast hτ
    rwa [Nat.cast_mul, Nat.cast_sub (by omega : 1 ≤ n), Nat.cast_one] at this
  have hn' : (2 : ℝ) ≤ n := by exact_mod_cast hn
  have hd' : (2 : ℝ) ≤ d := by exact_mod_cast hd
  have hI' : (n : ℝ) * d ≤ T.I := by exact_mod_cast hI
  have key : (n : ℝ) ^ 2 ≤ 31 * T.I * T.M := by
    have hτI : (n : ℝ) * (n - 1) ≤ 4 * T.M * (T.I + T.M) := by nlinarith
    rcases le_or_gt (4 * (T.M : ℝ)) n with h4 | h4
    · nlinarith
    · nlinarith
  have hsq : (n : ℝ) ^ 2 / T.M ≤ 31 * T.I := by
    rw [div_le_iff₀ hM]
    linarith
  linarith

/-! ### The analytic layer for one epoch -/

namespace History

/-- The Jacobian matrix of a map between coordinate spaces: entry `(i, j)` is `∂f_i/∂x_j`. -/
noncomputable def jacobian {m n : ℕ} (f : (Fin n → ℝ) → Fin m → ℝ) (x : Fin n → ℝ) :
    Matrix (Fin m) (Fin n) ℝ :=
  LinearMap.toMatrix' (fderiv ℝ f x : (Fin n → ℝ) →ₗ[ℝ] Fin m → ℝ)

theorem jacobian_apply {m n : ℕ} (f : (Fin n → ℝ) → Fin m → ℝ) (x : Fin n → ℝ) (i : Fin m)
    (j : Fin n) : jacobian f x i j = fderiv ℝ f x (Pi.single j 1) i :=
  LinearMap.toMatrix'_apply _ i j

end History

open OpenPath History

/-- **The chain rule in matrix form** (`eq:chain`). If `B = Φ ∘ C` with `C` differentiable at `x`
and `Φ` differentiable at `C x`, then `DB(x) = DΦ(C x) · DC(x)`. -/
theorem chain_rule_jacobian {p a b : ℕ} {C : (Fin p → ℝ) → Fin a → ℝ} {Φ : (Fin a → ℝ) → Fin b → ℝ}
    {x : Fin p → ℝ} (hC : DifferentiableAt ℝ C x) (hΦ : DifferentiableAt ℝ Φ (C x)) :
    jacobian (Φ ∘ C) x = jacobian Φ (C x) * jacobian C x := by
  rw [jacobian, fderiv_comp x hΦ hC]
  exact LinearMap.toMatrix'_comp _ _

/-- **Boundary factorisation, analytic core** (`lem:boundary`). Let the incoming values of an
epoch be the expressions `C k` in the inputs, and let each outgoing value be obtained by
substituting them into an expression `Φ i` in fresh arguments, as in the proof of
`lem:boundary`. If the executed outgoing expressions are division safe at a realised input `x₀`,
then `c ↦ (Φ i c)_i` is analytic on an open neighbourhood of the boundary point `C(x₀)`, and
`B(x) = Φ(C(x))` for every input. -/
theorem boundary_factorization {σ : Type*} [Fintype σ] {a b : ℕ} (C : Fin a → Expr σ)
    (Φ : Fin b → Expr (Fin a)) {x₀ : σ → ℝ} (hB : ∀ i, ((Φ i).subst C).Safe x₀) :
    ∃ N : Set (Fin a → ℝ), IsOpen N ∧ (fun k => (C k).eval x₀) ∈ N ∧
      AnalyticOnNhd ℝ (fun c i => (Φ i).eval c) N ∧
      ∀ x i, ((Φ i).subst C).eval x = (Φ i).eval (fun k => (C k).eval x) := by
  refine ⟨⋂ i, {c | (Φ i).Safe c}, isOpen_iInter_of_finite fun i => (Φ i).isOpen_setOf_safe,
    Set.mem_iInter.mpr fun i => (Φ i).safe_of_safe_subst C (hB i), fun c hc => ?_,
    fun x i => (Φ i).eval_subst C x⟩
  exact AnalyticAt.pi fun i => (Φ i).analyticAt_eval (Set.mem_iInter.mp hc i)

/-- **The chain rule for one epoch** (`eq:chain`). With incoming values `C`, outgoing values
`B = Φ ∘ C` and all executed divisions safe at `x`, the derivative of the outgoing values is
`DB(x) = Λ(x) DC(x)` with `Λ(x) = DΦ(C(x))`. Each entry of `Λ` is analytic in the inputs at
`x`. -/
theorem epoch_chain_rule {p a b : ℕ} (C : Fin a → Expr (Fin p)) (Φ : Fin b → Expr (Fin a))
    {x : Fin p → ℝ} (hC : ∀ k, (C k).Safe x) (hB : ∀ i, ((Φ i).subst C).Safe x) :
    jacobian (fun y i => ((Φ i).subst C).eval y) x =
        jacobian (fun c i => (Φ i).eval c) (fun k => (C k).eval x) *
          jacobian (fun y k => (C k).eval y) x ∧
      ∀ i k, AnalyticAt ℝ
        (fun y => jacobian (fun c i => (Φ i).eval c) (fun k => (C k).eval y) i k) x := by
  obtain ⟨N, hN, hxN, hΦN, hBΦ⟩ := boundary_factorization C Φ hB
  have hCan : AnalyticAt ℝ (fun y k => (C k).eval y) x :=
    AnalyticAt.pi fun k => (C k).analyticAt_eval (hC k)
  have hΦan : AnalyticAt ℝ (fun c i => (Φ i).eval c) (fun k => (C k).eval x) := hΦN _ hxN
  refine ⟨?_, fun i k => ?_⟩
  · have hfun : (fun y i => ((Φ i).subst C).eval y) =
        (fun c i => (Φ i).eval c) ∘ (fun y k => (C k).eval y) := by
      funext y i
      exact hBΦ y i
    rw [hfun]
    exact chain_rule_jacobian hCan.differentiableAt hΦan.differentiableAt
  · simp only [jacobian_apply]
    have hD : AnalyticAt ℝ (fderiv ℝ (fun c i => (Φ i).eval c)) (fun k => (C k).eval x) :=
      (hΦN.fderiv) _ hxN
    have hL : AnalyticAt ℝ (fun y => fderiv ℝ (fun c i => (Φ i).eval c)
        (fun k => (C k).eval y)) x := hD.comp hCan
    let ev : ((Fin a → ℝ) →L[ℝ] Fin b → ℝ) →L[ℝ] ℝ :=
      (ContinuousLinearMap.proj (R := ℝ) (φ := fun _ : Fin b => ℝ) i).comp
        (ContinuousLinearMap.apply ℝ (Fin b → ℝ) (Pi.single k 1))
    exact (ev.analyticAt _).comp hL

end ExactAttention
